deployment:
  tasks:
    - export DEPLOYPATH=/home/heavydu2/qmemoir.com/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R favicon.png $DEPLOYPATH